name: Run Tests
run-name: "#${{ github.run_number }} ${{ inputs.branch }} | ${{ inputs.env_name || inputs.custom_env_name }} | LM ${{ inputs.lm_version }}"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
      env_name:
        description: 'Tox environment name to run'
        required: true
        type: choice
        options:
          - wip
          - regression
          - performance
          - stress
          - system
          - sanity-patch
          - sanity-iso
          - security
          - qualys
          - nessus
          - kvm
          - kvm-patch
          - avaya
          - avaya-patch
          - xen
          - xen-patch
          - azure
          - azure-patch
          - aws
          - aws-patch
          - aws-marketplace-prepare
          - govcloud
          - govcloud-patch
          - govcloud-publish
          - hyperv
          - hyperv-patch
          - vsphere
          - vsphere-patch
          - centurylink
          - virtualbox
          - virtualbox-patch
          - templates
          - env
          - pester
          - scheduling
          - l7l4regression
          - l4l7checktype
          - http2regresssion
          - esptestsuite
          - espsamltestsuite
          - waftestsuite
          - certificate-regression
          - basicauth_espwithwaftestsuite
          - formauth_espwithwaftestsuite
          - contentruletestsuite
          - localcertsuit
          - cachemgmtsuit
          - usermgmttestsuit
          - l7-test
          - udp-test
          - api-test
          - ipv6-test
          - workflow-test
          - os-test
          - rs-test
          - ssl-test
          - ha-test
          - healthcheck-test
          - qualys_scans
          - gencheck_verification
          - artifacts
          - mt_release_test
          - lm_kemp360_integration
          - esp_sachin
          - ldap_sachin
          - sso_imageset
          - ecs_deploy
          - lm_live_migration
          - lm_release_task
          - lm_addon_validation
          - lm_template_validation
          - lm_geol7_http_checker
          - lm_geol7_https_checker
          - lm_abhishek
          - lm_custom
          - lm_lets_encrypt_certificate
          - azure_ha
          - snmp_validation
          - lm_qos_limiting
          - res_code_mapping
          - lm_digicert_nwc
          - lm_auto_install_addons
          - lm_auto_install_addons_upgrade
          - lm_persistence_with_failover
          - ha_configuration
          - lm_backup_and_restore
          - unit
          - dry-run
          - steps
          - tags
          - self
          - cucumber
          - testplan
          - layer4_ftp
        default: ''
      custom_env_name:
        description: 'Custom environment name (optional - use if not in dropdown)'
        required: false
        type: string
      extra_args:
        description: 'Extra arguments to pass to tox (optional)'
        required: false
        type: string
      lm_version:
        description: 'LoadMaster version to use for testing'
        required: true
        type: choice
        options:
          - LoadMaster-VLM-7.2.62.0.22915
          - LoadMaster-VLM-7.2.61.0.22763
        default: ''

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Run Production Security Scan
        run: echo "🔒 Running security audit on main branch..."





